---
version: "2"
services:
  motioneye:
    image: ccrisan/motioneye:master-armhf
    devices:
      - "/dev/video0"
    ports:
      - "8081:8081"
      - "8765:8765"
    environment:
      - TZ=America/New_York
    volumes_from:
      - data_motioneye

  data_motioneye:
    image: arm32v6/busybox
    volumes:
      - /home/pi/docker/motioneye/etc:/etc/motioneye
      - /home/pi/docker/motioneye/media:/var/lib/motioneye

